### ISSUE TITLE
convert over NetFS

### ISSUE THREAD

**Issue by landmanbester** [ratt-ru/dask-ms#280]
* dask-ms version: master branch
* Python version: 3.8-3.10
* Operating System: ubuntu20.04

### Description

Documenting this one because I think it would be useful to have this functionality. I am trying to run dask-ms convert over /net and it's falling over (see below). For reference I can do this with CASA's split just fine. 

### What I Did

Running
```
$ dask-ms convert /net/sinatra/vault-ike/oms/MeerKAT-data/ESO137/1557347448_sdp_l0.ms -g "FIELD_ID,DATA_DESC_ID,SCAN_NUMBER" -o test.zarr --chunks="{row:50000,chan:256}" --format zarr --force --taql-where "FIELD_ID==0"
```
fails with
```
2023-08-01 08:20:51     INFO            Process 2047757: waiting for write-lock on file /net/sinatra/vault-ike/oms/MeerKAT-data/ESO137/1557347448_sdp_l0.ms/table.lock
Traceback (most recent call last):
  File "/home/bester/.venv/qcal/bin/dask-ms", line 8, in <module>
    sys.exit(main())
  File "/home/bester/.venv/qcal/lib/python3.8/site-packages/daskms/apps/entrypoint.py", line 9, in main
    return EntryPoint(sys.argv[1:]).execute()
  File "/home/bester/.venv/qcal/lib/python3.8/site-packages/daskms/apps/entrypoint.py", line 33, in execute
    cmd.execute()
  File "/home/bester/.venv/qcal/lib/python3.8/site-packages/daskms/apps/convert.py", line 191, in execute
    writes = self.convert_table(self.args)
  File "/home/bester/.venv/qcal/lib/python3.8/site-packages/daskms/apps/convert.py", line 229, in convert_table
    datasets = reader(args.input, chunks=args.chunks)
  File "/home/bester/.venv/qcal/lib/python3.8/site-packages/daskms/dask_ms.py", line 330, in xds_from_ms
    return xds_from_table(
  File "/home/bester/.venv/qcal/lib/python3.8/site-packages/daskms/dask_ms.py", line 291, in xds_from_table
    return DatasetFactory(
  File "/home/bester/.venv/qcal/lib/python3.8/site-packages/daskms/reads.py", line 474, in datasets
    datasets = self._group_datasets(table_proxy, groups, exemplar_rows, orders)
  File "/home/bester/.venv/qcal/lib/python3.8/site-packages/daskms/reads.py", line 388, in _group_datasets
    group_var_dims = _dataset_variable_factory(
  File "/home/bester/.venv/qcal/lib/python3.8/site-packages/daskms/reads.py", line 251, in _dataset_variable_factory
    table_proxy.setmaxcachesize(column, 1).result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 444, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/bester/.venv/qcal/lib/python3.8/site-packages/daskms/table_proxy.py", line 111, in _impl
    table.lock(write=True)
  File "/home/bester/.venv/qcal/lib/python3.8/site-packages/casacore/tables/table.py", line 726, in lock
    self._lock(write, nattempts)
RuntimeError: Error (Bad file descriptor) when acquiring lock on /net/sinatra/vault-ike/oms/MeerKAT-data/ESO137/1557347448_sdp_l0.ms/table.lock
```
Looks like it's failing because I don't have write permissions to the origin but then I am not sure why I should need them

**Comment by sjperkins** [comment]
Thanks for reporting tihs.

For my own reference, its strange that this is happening as AFAICT dask-ms should be opening the source dataset as read only in `xds_from_ms` style operations

https://github.com/ratt-ru/dask-ms/blob/815bb48665d662366de095c89b9fa034ffb154e8/daskms/reads.py#L319-L327

as well as in the `convert` app

https://github.com/ratt-ru/dask-ms/blob/815bb48665d662366de095c89b9fa034ffb154e8/daskms/apps/formats.py#L29-L35

**Comment by sjperkins** [comment]
Looking at the stacktrace more closely, it's because `setmaxcachesize` is used with a write lock.
